[package]
name = "sandbox"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
utility = { path = "../utility" }
tessera = { path = "../tessera" }
pleroma = { path = "../pleroma" }
aether = { path = "../aether" }
aer = { path = "../aer" }
cosmo = { path = "../cosmo" }
nexus = { path = "../nexus" }
eidolon = { path = "../eidolon", features = ["bevy"] }
terra = { path = "../terra" }
lumen = { path = "../lumen" }
thalassa = { path = "../thalassa" }
syzygy = { path = "../syzygy" }
bevy = "0.18.1"
bevy_panorbit_camera = "0.34.0"

[dev-dependencies]
tempfile = "3"
