[package]
name = "sandbox"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
utility = { path = "../utility" }
tessera = { path = "../tessera" }
pleroma = { path = "../pleroma" }
aether = { path = "../aether" }
aer = { path = "../aer" }
cosmo = { path = "../cosmo" }
nexus = { path = "../nexus" }
eidolon = { path = "../eidolon" }
terra = { path = "../terra" }
lumen = { path = "../lumen" }
