// Copyright 2026 William Probyn
// SPDX-License-Identifier: Apache-2.0

//! Diagnostics traits for fixed-size state vectors.
//!
//! Three traits cover three distinct extraction patterns over a state
//! `[f64; N]` carried by a type that knows the law / model parameters:
//!
//! - [`Diagnostics`] — pass-through component names. Default iter zips
//!   declared names with raw state values.
//! - [`ExtraDiagnostics`] — derived per-cell quantities (temperature,
//!   pressure, kinetic energy). User-defined.
//! - [`ConservationQuantities`] — declares which raw components integrate
//!   to volume-weighted conserved totals. The integration itself lives in
//!   `continuum::diagnostics::integrate_conserved` because it requires a
//!   mesh and field, which are concepts above this crate.
//!
//! All three are typically generated by `#[derive(StateDiagnostics)]` from
//! a single annotation block; manual impls remain valid for cases the
//! derive can't express.

/// Pass-through component diagnostics. Implementing types declare the
/// names of their state components; the default iter zips them with the
/// raw state values.
pub trait Diagnostics<const N: usize> {
  const COMPONENT_NAMES: [&'static str; N];

  fn diagnostics<'a>(
    &'a self,
    state: &'a [f64; N],
  ) -> impl Iterator<Item = (&'static str, f64)> + 'a {
    Self::COMPONENT_NAMES
      .iter()
      .copied()
      .zip(state.iter().copied())
  }
}

/// Derived per-cell quantities — temperature, pressure, kinetic energy,
/// etc. The implementing type computes these from the raw state using its
/// law parameters. Returned as an iterator of named values; impls
/// typically build a fixed-size array and call `into_iter` to avoid heap
/// allocation per cell.
pub trait ExtraDiagnostics<const N: usize> {
  fn extras<'a>(
    &'a self,
    state: &'a [f64; N],
  ) -> impl Iterator<Item = (&'static str, f64)> + 'a;
}

/// Identifies one component of a state vector that integrates to a
/// conserved total when multiplied by cell volume and summed over the
/// domain.
#[derive(Clone, Copy, Debug)]
pub struct ConservedQuantity<const N: usize> {
  pub name: &'static str,
  pub component: usize,
}

/// Metadata declaring which components of a state vector are conservation
/// totals. The actual volume-weighted integration lives in
/// `continuum::diagnostics::integrate_conserved` — this trait is just the
/// declaration so callers can drive that reducer without hand-listing
/// indices and names per call site.
pub trait ConservationQuantities<const N: usize> {
  const CONSERVED_QUANTITIES: &'static [ConservedQuantity<N>];
}
