// Copyright 2026 William Probyn
// SPDX-License-Identifier: Apache-2.0

pub mod collections;
pub mod constants;
pub mod domain;
pub mod error;
pub mod logger;
pub mod maths;
pub mod profiler;
pub mod serial;
pub mod thread;

pub use utility_macros::Deserialize;
pub use utility_macros::Serialize;
pub use utility_macros::profile;

extern crate self as utility;

pub mod consts {
  pub use crate::constants::{
    EARTH_ALBEDO, EARTH_AXIAL_TILT, EARTH_DAY, EARTH_MASS, EARTH_ORBIT,
    EARTH_RADIUS, EARTH_SURFACE_P, EARTH_SURFACE_T, JUPITER_AXIAL_TILT,
    JUPITER_DAY, JUPITER_HEAT_FACTOR, JUPITER_MASS, JUPITER_ORBIT,
    JUPITER_RADIUS, JUPITER_SURFACE_T, MARS_ALBEDO, MARS_AXIAL_TILT, MARS_DAY,
    MARS_MASS, MARS_ORBIT, MARS_RADIUS, MARS_SURFACE_P, MARS_SURFACE_T,
    MERCURY_AXIAL_TILT, MERCURY_DAY, MERCURY_MASS, MERCURY_ORBIT,
    MERCURY_RADIUS, MERCURY_SURFACE_P, MERCURY_SURFACE_T, NEPTUNE_AXIAL_TILT,
    NEPTUNE_DAY, NEPTUNE_HEAT_FACTOR, NEPTUNE_MASS, NEPTUNE_ORBIT,
    NEPTUNE_RADIUS, NEPTUNE_SURFACE_T, NOMINAL_GAS_PRESS, SATURN_AXIAL_TILT,
    SATURN_DAY, SATURN_HEAT_FACTOR, SATURN_MASS, SATURN_ORBIT, SATURN_RADIUS,
    SATURN_SURFACE_T, SOLAR_CORE_TEMP, SOLAR_MASS, SOLAR_RADIUS,
    SOLAR_SURFACE_TEMP, VENUS_ALBEDO, VENUS_AXIAL_TILT, VENUS_DAY, VENUS_MASS,
    VENUS_ORBIT, VENUS_RADIUS, VENUS_SURFACE_P, VENUS_SURFACE_T,
  };
}
