[workspace]
members = [
  "utility",
  "utility/xtask",
  "sandbox",
  "continuum",
  "aer",
  "cosmo",
  "gravitas",
  "lumen",
  "nexus",
  "eidolon",
  "terra",
  "tempus",
  "pleroma",
  "tessera",
  "syzygy",
  "thalassa",
  "aether",
]

resolver = "2"

[workspace.package]
license = "Apache-2.0"
